### ISSUE TITLE
Set api-gateway as origin for cloudFront resource

### ISSUE THREAD

**Issue by gustavobertolino** [sashee/cloudfront-multiple-origins#1]
Hi, Tamás @sashee . I'm working on a task in which I have to do something pretty similar to what you've done in your Terraform script for creating cloudfront with multiple origin. In my case I want to set a specific API Gateway to my CloudFront distro resource, in the origin's variable, like you did as follows

![image](https://user-images.githubusercontent.com/25723294/88082606-5ad9b880-cb58-11ea-84d7-70b3e94c8c0a.png) 

After following your template, my script is still returning error, indicating that Terraform doesn't accept the origin I set, as if it were an invalid origin, as follows

https://ibb.co/km1pbkN (screen with the Terraform's error message)

**Comment by sashee** [comment]
Hey @gustavobertolino ,

it seems like that CloudFront thinks the domain should be an S3 bucket. Maybe you have an ```s3_origin_config``` for this origin?

Other than that, this whole replace thing does nothing but extract a part from the ```aws_api_gateway_deployment.deployment.invoke_url```. You can debug it by adding an output and set the value to ```replace(...)``` and see what Terraform tries to set for the domain_name. This might add a clue what's wrong.

**Comment by gustavobertolino** [comment]
Yep, I did exactly as you. I set this `replace` function to extract the value of my variable `invoke_url`, as follows

https://ibb.co/gMjPyQF

But Terraform keeps returning the same error. I'll set an output for it and set the value again so that I can see what Terrafomr is trying to set in this case.

**Comment by gustavobertolino** [comment]
About the output command, you're suggesting to make something like `terraform output` or `terraform output [variable]` or any variation of them, aren't you?

https://www.terraform.io/docs/commands/output.html

**Comment by sashee** [comment]
Yes, just to debug the value.

Just to confirm: if you deploy [my stack](https://github.com/sashee/cloudfront-multiple-origins/blob/master/main.tf) does that work?

**Comment by gustavobertolino** [comment]
I output the value yesterday running the command, double-checked it and I assured that it is my APIGw domain indeed. But the same error is returned :(

About your stack, no I didn't because I'm working on it from my company's computer. Besides, I should deploy your stack on another AWS account other than my company's AWS development account, because it gets deployed already a Terraform stack and there are security restrictions to do it also.

I'll try your stack on my personal AWS account. Let's see...

**Comment by gustavobertolino** [comment]
I identified the problem... I was missing the custom_origin_config and it was preventing TF from looking at origin as an APIGw, I guess

![image](https://user-images.githubusercontent.com/25723294/88417879-1c8f0400-cdb9-11ea-96c8-1c86d73b0643.png)

**Comment by sashee** [comment]
Great! It seems like without that block cf thinks this is an S3 origin and then saw that the domain is not for a bucket, hence the error.

**Comment by gustavobertolino** [comment]
It's interesting that TF documentation is not clear about the obligation of this attribute specifically, contrary to the others.

![image](https://user-images.githubusercontent.com/25723294/88418147-7bed1400-cdb9-11ea-89c1-e2bb1568f7a7.png)
